# SPDX-FileCopyrightText: 2023 Veit Schiele
#
# SPDX-License-Identifier: BSD-3-Clause

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
